/*
 * Gurjit Singh
 * Monday October 28th - 2019
 * This program displays the string methods
 */

/**
 *
 * @author sangha
 */
public class frmstringmethods extends javax.swing.JFrame {

    /**
     * Creates new form frmstringmethods
     */
    public frmstringmethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        lblSixth = new javax.swing.JLabel();
        lblSeventh = new javax.swing.JLabel();
        lblEighth = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        txtFourth = new javax.swing.JTextField();
        txtFifth = new javax.swing.JTextField();
        txtSixth = new javax.swing.JTextField();
        txtSeventh = new javax.swing.JTextField();
        txtEighth = new javax.swing.JTextField();
        txtNinth = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnSecond = new javax.swing.JButton();
        btnThird = new javax.swing.JButton();
        btnFourth = new javax.swing.JButton();
        btnFifth = new javax.swing.JButton();
        btnSixth = new javax.swing.JButton();
        btnSeventh = new javax.swing.JButton();
        lblNinth = new javax.swing.JLabel();
        lblTenth = new javax.swing.JLabel();
        lblEleventh = new javax.swing.JLabel();
        lblTwelfth = new javax.swing.JLabel();
        lblThirteenth = new javax.swing.JLabel();
        lblFourteenth = new javax.swing.JLabel();
        lblFifteenth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirst.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(153, 0, 102));
        lblFirst.setText("String Methods");
        getContentPane().add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        lblSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(255, 51, 255));
        lblSecond.setText("Enter a string. The program will output the number of characters in the string:");
        getContentPane().add(lblSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblThird.setForeground(new java.awt.Color(255, 51, 255));
        lblThird.setText("Enter a string using lowercase letters. The program will output the string in all capital letters:");
        getContentPane().add(lblThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblFourth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFourth.setForeground(new java.awt.Color(255, 51, 255));
        lblFourth.setText("Enter a string. The program will output the character at the 4th spot:");
        getContentPane().add(lblFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lblFifth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFifth.setForeground(new java.awt.Color(255, 51, 255));
        lblFifth.setText("Enter two strings. The program will output wheter or not they are identical:");
        getContentPane().add(lblFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        lblSixth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSixth.setForeground(new java.awt.Color(255, 51, 255));
        lblSixth.setText("Enter a string and a letter. The program will output whether or not the letter is found in the string:");
        getContentPane().add(lblSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        lblSeventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblSeventh.setForeground(new java.awt.Color(255, 51, 255));
        lblSeventh.setText("Enter a string that is at leat 8 characters long. The program will output characters 4 to 6:");
        getContentPane().add(lblSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        lblEighth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblEighth.setForeground(new java.awt.Color(255, 51, 255));
        lblEighth.setText("Enter a string that contains at least one \"a\". The program will then replace all occurences of the letter \"a\" with \"x\":");
        getContentPane().add(lblEighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        txtFirst.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, -1));

        txtSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, -1));

        txtThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, -1));

        txtFourth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 120, -1));

        txtFifth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 120, -1));

        txtSixth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 120, -1));

        txtSeventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 70, -1));

        txtEighth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtEighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 120, -1));

        txtNinth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        getContentPane().add(txtNinth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 120, -1));

        btnFirst.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnFirst.setText("Length");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnSecond.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnSecond.setText("All Caps");
        btnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        btnThird.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnThird.setText("4th Character");
        btnThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdActionPerformed(evt);
            }
        });
        getContentPane().add(btnThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        btnFourth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnFourth.setText("Identical or not?");
        btnFourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourthActionPerformed(evt);
            }
        });
        getContentPane().add(btnFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        btnFifth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnFifth.setText("Letter Found or not?");
        btnFifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFifthActionPerformed(evt);
            }
        });
        getContentPane().add(btnFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        btnSixth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnSixth.setText("Characters 4 to 6");
        btnSixth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixthActionPerformed(evt);
            }
        });
        getContentPane().add(btnSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        btnSeventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        btnSeventh.setText("Replace \"a\"");
        btnSeventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeventhActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        lblNinth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblNinth.setText("--------------------");
        getContentPane().add(lblNinth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        lblTenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblTenth.setText("--------------------");
        getContentPane().add(lblTenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        lblEleventh.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblEleventh.setText("--------------------");
        getContentPane().add(lblEleventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        lblTwelfth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblTwelfth.setText("--------------------");
        getContentPane().add(lblTwelfth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        lblThirteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblThirteenth.setText("--------------------");
        getContentPane().add(lblThirteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        lblFourteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFourteenth.setText("--------------------");
        getContentPane().add(lblFourteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, -1, -1));

        lblFifteenth.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblFifteenth.setText("--------------------");
        getContentPane().add(lblFifteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        String word = (txtFirst.getText());
        double length = word.length();
        String length1 = String.valueOf(length);
        
        lblNinth.setText(length1);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondActionPerformed
        String word = (txtSecond.getText());
        String allcaps = word.toUpperCase();
        
        lblTenth.setText(allcaps);
    }//GEN-LAST:event_btnSecondActionPerformed

    private void btnThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdActionPerformed
        String word = (txtThird.getText());
        char fourthspot = word.charAt(3);
        String fourthspot1 = String.valueOf(fourthspot);
        
        lblEleventh.setText(fourthspot1);
    }//GEN-LAST:event_btnThirdActionPerformed

    private void btnFourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourthActionPerformed
        String word = (txtFourth.getText());
        String word2 = (txtFifth.getText());
        boolean output = word.equals(word2);
        
        if (output == true) {
            lblTwelfth.setText("Identical");
        }
        else {
            lblTwelfth.setText("Not Identical");
        }
        
    }//GEN-LAST:event_btnFourthActionPerformed

    private void btnFifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFifthActionPerformed
        String word = (txtSixth.getText());
        String letter = (txtSeventh.getText());
        
        if (word.contains(letter)) {
            lblThirteenth.setText("Yes");
        }
        else {
            lblThirteenth.setText("No");
        }
    }//GEN-LAST:event_btnFifthActionPerformed

    private void btnSixthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixthActionPerformed
        String word = (txtEighth.getText());
        char spots = word.charAt(3);
        char spots1 = word.charAt(4);
        char spots2 = word.charAt(5);
        String spotstotal = String.valueOf(spots);
        String spotstotal1 = String.valueOf(spots1);
        String spotstotal2 = String.valueOf(spots2);
        
        lblFourteenth.setText(spotstotal + spotstotal1 + spotstotal2);
    }//GEN-LAST:event_btnSixthActionPerformed

    private void btnSeventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeventhActionPerformed
        String word = (txtNinth.getText());
        String replaced = word.replace("a", "x");
        
        lblFifteenth.setText(replaced);
    }//GEN-LAST:event_btnSeventhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmstringmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmstringmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmstringmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmstringmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmstringmethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFifth;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFourth;
    private javax.swing.JButton btnSecond;
    private javax.swing.JButton btnSeventh;
    private javax.swing.JButton btnSixth;
    private javax.swing.JButton btnThird;
    private javax.swing.JLabel lblEighth;
    private javax.swing.JLabel lblEleventh;
    private javax.swing.JLabel lblFifteenth;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourteenth;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblNinth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblSeventh;
    private javax.swing.JLabel lblSixth;
    private javax.swing.JLabel lblTenth;
    private javax.swing.JLabel lblThird;
    private javax.swing.JLabel lblThirteenth;
    private javax.swing.JLabel lblTwelfth;
    private javax.swing.JTextField txtEighth;
    private javax.swing.JTextField txtFifth;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtFourth;
    private javax.swing.JTextField txtNinth;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtSeventh;
    private javax.swing.JTextField txtSixth;
    private javax.swing.JTextField txtThird;
    // End of variables declaration//GEN-END:variables
}
